### ISSUE TITLE
[migrate to AWS] migrate from webapp2 to flask

### ISSUE THREAD

**Issue by aniri** [code4romania/redirectioneaza#10]
redirectioneaza.ro is built to work on Google App engine and it has a lot of dependencies on it..
In order to make the transition to AWS, all the connections to Google's platform must be stripped.

**migrate from webapp2 to flask**
webapp2 is a very stable micro framework but not very known outside of app engine. if a migration to flask would be necessary we can definitely take it into consideration

**Comment by onel** [comment]
Hey @Andu033  thanks for the interest. We've started working on this on our last hackathon but we couldn't finish. There are still some small things to do.
I can bring you up to date with the changes that are still needed, so we can finish this.
Let me know.

**Comment by Andu033** [comment]
@onel  sounds good
