### ISSUE TITLE
The link from the success page is incorrect

### ISSUE THREAD

**Issue by LiviaSarban** [code4romania/redirectioneaza#113]
**URL:** https://redirectioneaza.ro/code-for-romania/succes
**Code:** https://github.com/code4romania/redirectioneaza/blob/custom-subdomains/views/succes.html#L33

In `Chrome Version 101.0.4951.64 (Official Build) (x86_64)`, the URL becomes https://redirectioneaza.ro/redirectioneaza.ro

Afaik, using an absolute path should fix the problem.

**Comment by onel** [comment]
Thanks for opening the issue. Fixed with the latest deploy.
