### ISSUE TITLE
Trying to add an NGO that already exists crashes the page

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/redirectioneaza#205]
**Describe the bug**
Trying to add an NGO that already exists crashes the page

**To Reproduce**
1. Go to [Înregistrează ONG] with a new user (not the one that created the NGO)
2. Use the name of an existing NGO
3. Submit the new NGO

**Expected behavior**
A validation message blocking the user from submitting the form

**Screenshots**
![image](https://github.com/code4romania/redirectioneaza/assets/56204138/052402e6-2b2e-4de2-814f-001bed59e323)

Desktop (please complete the following information):
OS: [windows 10 pro Version 10.0.19045 Build 19045]
Browser [chrome]
Version [Version 120.0.6099.225]

**Comment by tudoramariei** [comment]
Fixed the validation to not crash
