### ISSUE TITLE
Updating an NGO as Admin does not work

### ISSUE THREAD

**Issue by danniel** [code4romania/redirectioneaza#38]
The code for updating an NGO first checks if the user already has an NGO. If the user has no NGO, then a new one is created. If the user already has an NGO, then that organisation is updated.

The problem is that there doesn't seem to be any way for the Admin account to edit another NGO. When one tries to update an existing organisation, the code tries to create a new NGO because the Admin has no NGO.

**Comment by cnstlungu** [comment]
Thanks @danniel . 

@onel I would think this issue is no longer actual given the changes we've made for #28 .
Updating an NGO as an admin should be done solely through the Admin interface. Opinions?

**Comment by onel** [comment]
@danniel thanks for finding this and taking the time to create a PR. 
It fixes the issue, but as @cnstlungu said, we have moved all the admin functionality to a different part of the app. It was hacky the way it was done up to now.
Closing this issue
