### ISSUE TITLE
[migrate to AWS] migrate from Datastore to Postgres

### ISSUE THREAD

**Issue by aniri** [code4romania/redirectioneaza#6]
redirectioneaza.ro is built to work on Google App engine and it has a lot of dependencies on it..
In order to make the transition to AWS, all the connections to Google's platform must be stripped.

**migrate from Datastore to Postgres**
As a storage we use Datastore, the NoSql DB from google. I think Postgres would be a good replacement. This change would mean recreating the models, ORM and migrating all the data

**Comment by onel** [comment]
A TODO list for this issue:

- [ ] integrate postgres in the app (making/destroying connections, etc)
- [ ] change the ORM from ndb to something else (django, etc)
- [ ] replace all the queries in the app to use the new models
