### ISSUE TITLE
[migrate to AWS] put a web server in front

### ISSUE THREAD

**Issue by aniri** [code4romania/redirectioneaza#7]
redirectioneaza.ro is built to work on Google App engine and it has a lot of dependencies on it..
In order to make the transition to AWS, all the connections to Google's platform must be stripped.

**put a web server in front**
App engine offers their own web server. it also has auto scaling, etc

**Comment by onel** [comment]
This is not needed anymore.
We'll be using Elastic Beanstalk which will take care of it.
