### ISSUE TITLE
Optionally send the form by email to the NGO

### ISSUE THREAD

**Issue by andreeib** [code4romania/redirectioneaza#74]
Instead of requiring the user to print and send the form to ANAF or the NGO add the option to send it via email to the NGO who should take care of printing and submitting.

This will decrease the work that needs to be done to submit the form and encourage more users to do it.
There are alot of persons that postpone and forget or don't submit the form because of the extra work that needs to be done.

### Flow:
- We mark in the DB the NGOs that support this option
- For NGO that support in the download form step we add a "Send by email" button
- If the button is pressed we send an email with the form to the NGO
- Congratulate the user and allow to share his deed on Facebook ...
- When the time comes the NGO downloads all forms from email, prints and submits them to ANAF

What do you think?

**Comment by thewindev** [comment]
Sounds cool, that would really boost the number of submissions. If this is legal then it won't be that hard to implement, we just have to make sure that a form is taken into consideration if it's only sent by email. Before the pandemic I remember that this was not really ok, maybe things changed though...

**Comment by andreeib** [comment]
There are some NGOs that already allow to submit the form electronically:
https://casaluipatrocle.ro/formular-230/
https://helpautism.ro/formular230/RO90BACX0000000843775216
From my understanding they print the PDFs and submit them.

The legislation changed last year:
https://www.g4media.ro/anaf-cetatenii-pot-trimite-formularul-230-de-redirectionare-a-2-din-impozitul-pe-venit-si-prin-curier-sau-scanate-online-de-catre-ong-urile-beneficiare.html

**Comment by andreeib** [comment]
This is an interesting take from the NGOs side on why it's not a good idea for them to handle the forms:
https://www.tac.social/post/pe-buna-dreptatea-lui-2

**Comment by catileptic** [comment]
Hello, @andreeib, and hey there, @thewindev!

The good news is that we have already implemented this feature!
If an NGO toggles a check in their profile, saying they will accept forms sent to them by e-mail, the "success" page that the user sees offers them this option explicitly. 

However, it's really important to not that ANAF has said, time and time again, this year, that no form is valid unless it has been signed by hand. So, the user still has to print out the form, sign it then scan it or take a very good picture of it. After this, they can send the form to the NGO by e-mail, as the platform instructs them to. 

A form without a hand-drawn signature is not valid, in the words of ANAF so we can not, under any circumstance, skip the step of telling the user to sign the form. 

If a user has a qualified, official electronic signature, they can use that to sign the form. However, most people don't.

**Comment by andreeib** [comment]
Hey @catileptic, good to know that this feature already exists.
As you said because of legislation and ANAFs procedures I don't think anymore that this is a good way to submit the forms.

So for now I'll stick to encouraging people to register to ANAF SPV using video identification so they can submit the form online:
https://www.anaf.ro/InregPersFizicePublic/formularInregistrare.jsp

I'll close this issue. Thank you.
