### ISSUE TITLE
[migrate to AWS] google cloud -> S3

### ISSUE THREAD

**Issue by aniri** [code4romania/redirectioneaza#9]
redirectioneaza.ro is built to work on Google App engine and it has a lot of dependencies on it..
In order to make the transition to AWS, all the connections to Google's platform must be stripped.

**google cloud -> S3**
All the static assets (logos, etc) and the PDF documents that are created after a donor completes the form are uploaded to google cloud.
We would like to start using S3 for this

**Comment by cnstlungu** [comment]
This has been migrated from google cloud. It's platform-agnostic at the moment, using mocks for the storage part. Can we please update the issue title to 'Migrate to AWS Cloud - S3 + Elastic Beanstalk'

**Comment by tudoramariei** [comment]
[Solved in v2](https://github.com/code4romania/redirectioneaza/releases/tag/v2.0.0)
